### ISSUE TITLE
The `test-sa` workaround fails with microk8s 1.24

### ISSUE THREAD

**Issue by sed-i** [charmed-kubernetes/actions-operator#37]
Not sure if this is the right place to report this, but:

When attempting the `microk8s.kubectl create serviceaccount test-sa` workaround, the script times out with
`No resources found in default namespace.`

https://github.com/charmed-kubernetes/actions-operator/blob/30b48933eb056ae6660b279ba23f0d3c4b57326b/src/bootstrap/index.ts#L44-L48

- Setup works with microk8s 1.23 ([example](https://github.com/canonical/prometheus-k8s-operator/runs/6417196864?check_suite_focus=true#step:3:79))
- Setup fails with microk8s 1.24 ([example](https://github.com/canonical/prometheus-k8s-operator/runs/6426956758?check_suite_focus=true#step:3:179))

**Comment by stonepreston** [comment]
This is due to the [LegacyServiceAccountTokenNoAutoGeneration feature gate](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes) being enabled by default. Secrets are no longer generated automatically when a service account is created.

**Comment by addyess** [comment]
to expand on the comment from @stonepreston, microk8s 1.24 states that service tokens are not automatically generated.  One test that the actions-operator takes is to test that rbac is functional by creating a service account and then getting the service token for that account.  Two options for work arounds are changing the version of microk8s used in the test with

```yaml
jobs:
  test-on-microk8s:
    runs-on: ubuntu-latest
    name: Test on Microk8s
    steps:
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.23/stable
```
