### ISSUE TITLE
Not working with strict microk8s

### ISSUE THREAD

**Issue by jnsgruk** [charmed-kubernetes/actions-operator#42]
Hey!

I've been doing some experimentation with Juju 3.0 and Microk8s 1.25/strict in Github Actions prior to the 3.0 release.

We're about to hit a fairly big problem across a bunch of teams, in that currently the `actions-operator` is hardcoded to add the user to the `microk8s` group, which doesn't exist with the strict microk8s snap (it uses `snap_microk8s`).

Given that with Juju 3.0 using strict microk8s is a hard requirement, we probably want to sort this before it releases some time during this week

Issue demonstrated here: https://github.com/jnsgruk/parca-k8s-operator/actions/runs/3265300610/jobs/5367304679#step:3:114

with the following:

```yaml
- name: Setup operator environment
  uses: charmed-kubernetes/actions-operator@main
  with:
    provider: microk8s
    channel: 1.25-strict/stable
    juju-channel: 3.0/candidate
```
