### ISSUE TITLE
Means to itest integrations between machine and k8s charm

### ISSUE THREAD

**Issue by sed-i** [charmed-kubernetes/actions-operator#52]
I would like to write an itest for integrating a machine charm with cos lite.
I wonder if it could be possible to specify multiple providers:

```yaml
jobs:
#...
        with:
          providers:
          - cloud: microk8s
            microk8s-addons: "storage dns"
          - cloud: lxd
```
