### ISSUE TITLE
microk8s-channel needed.

### ISSUE THREAD

**Issue by hmlanigan** [charmed-kubernetes/actions-operator#61]
There is an 'lxd-channel', 'juju-channel' etc., however not one for microk8s. Using 'channel' results in confusion with the lxd channel. 

I have this matrix setup:
```yaml
    strategy:
      fail-fast: false
      matrix:
        # Different clouds
        cloud:
          - "lxd"
          - "microk8s"
        terraform:
          - "1.4.*"
          - "1.5.*"
          - "1.6.*"
        juju:
          - "3.1/stable"
```
and this test step:
```yaml
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: ${{ matrix.cloud }}
          juju-channel: ${{ matrix.juju }}
          channel: "1.28-strict/stable"
```
However I want the channel to only apply to microk8s, not lxd. Juju 3.1 requires a strictly confined version of microk8s, thus I have to specify the channel as its not default.

**Comment by addyess** [comment]
LXD will always be installed by the actions-operator, it's required by charmcraft to build charms.  But lxd can also be the provider (ie -- juju will deploy onto it).  This presents a bit of a inputs dichotomy which should have been handled when the actions-operator starting snap installing `charmcraft`.  

`channel` was meant to represent the provider's channel if the provider that can be snap installed such as in lxd, microk8s, microstack, etc...  

Somewhere along the way `lxd-channel` was added and now this issue requests `microk8s-channel` be added.

Lets consider the simplest scenarios for the `actions-operator` which requires the `provider` and `channel` 

1) 
```yaml
      - name: Setup lxd environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          channel: 5.19/stable
```
2) 
```yaml
      - name: Setup microk8s environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.28-strict/stable
```
3) 
```yaml
      - name: Setup lxd environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          channel: 1.28-strict/stable
```


in scenario (1), lxd is installed via the `lxd-channel=latest/stable` but then refreshed to `5.19/stable`, microk8s is never installed
in scenario (2), lxd is installed via the `lxd-channel=latest/stable` and microk8s installed to `1.28-strict/stable`
No trouble so far
in scenario (3), lxd is installed via the `lxd-channel=latest/stable` but then refreshed to an invalid `1.28-strict/stable`, microk8s is never installed

I would contend that scenario 3 represents an invalid argument set.  There is no `1.28-strict/stable` channel for `lxd` and should error.

@hmlanigan would you be open to considering a different matrix strategy?

```yaml
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.4.*"
          - "1.5.*"
          - "1.6.*"
        juju:
          - "3.1/stable"
        # Different clouds
        include:
           - cloud: lxd
             channel: 5.19/stable
           - cloud: microk8s
             channel: 1.28-strict/stable
```

and test-step

```yaml
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: ${{ matrix.cloud }}
          channel: ${{ matrix.channel }}
          juju-channel: ${{ matrix.juju }}
```
