### ISSUE TITLE
Regression when setting up the environment

### ISSUE THREAD

**Issue by deusebio** [charmed-kubernetes/actions-operator#84]
Hi!

We are using the `charmed-kubernetes/actions-operator` to setup a K8s environment in our CI, using

```
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: microk8s
          channel: 1.28-strict/stable
          bootstrap-options: " --agent-version 3.4.3"
          microk8s-group: snap_microk8s
          microk8s-addons: "rbac dns minio metallb:${{ env.IPADDR }}-${{ env.IPADDR }}"
```

However since last night (commit [b93f71](https://github.com/charmed-kubernetes/actions-operator/commit/b93f71025935ade47eea99d4369c3605c18c576c)), CI started to break with some errors when accessing to some env level information, such as 

```
lightkube.core.exceptions.ConfigError: Configuration file ~/.kube/config not found
```

and

```
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
```

Has anything changed in this respect with the last commit?

[This](https://github.com/canonical/spark-k8s-bundle/actions/runs/11024538944/job/30625655136) is one of the CI that is currently failing. Also it seems that pinning the previous commit (see [PR](https://github.com/canonical/spark-k8s-bundle/pull/46)) fixes this
